ChoiceVisualizer/Models/Card.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KitProjects.ChoiceVisualizer.Models
{
    public class Card<T>
    {
        public T Choice { get; set; }
        public bool Selected { get; set; }
    }
}

ChoiceVisualizer/Models/ErrorViewModel.cs
using System;

namespace ChoiceVisualizer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChoiceVisualizer/Models/FinalsViewModel.cs
using KitProjects.EnterpriseLibrary.Core.Models;
using System.Collections.Generic;

namespace KitProjects.ChoiceVisualizer.Models
{
    public class FinalsViewModel
    {
        public Card<Choice> First { get; set; }
        public Card<Choice> Second { get; set; }
        public List<Card<Choice>> ThirdPlaceContestants { get; set; }
    }
}

ChoiceVisualizer/Models/ResultsViewModel.cs
using KitProjects.EnterpriseLibrary.Core.Models;

namespace KitProjects.ChoiceVisualizer.Models
{
    public class ResultsViewModel
    {
        public Card<Choice> Winner { get; set; }
        public Card<Choice> SecondPlace { get; set; }
        public Card<Choice> ThirdPlace { get; set; }
    }
}

ChoiceVisualizer/Models/RoundViewModel.cs
using KitProjects.EnterpriseLibrary.Core.Models;
using System.Collections.Generic;

namespace KitProjects.ChoiceVisualizer.Models
{
    public class RoundViewModel
    {
        public List<Card<Choice>> FirstHalf { get; set; }
        public List<Card<Choice>> SecondHalf { get; set; }
    }
}

ChoiceVisualizer/Models/SemiFinalsViewModel.cs
using KitProjects.EnterpriseLibrary.Core.Models;
using System.Collections.Generic;

namespace KitProjects.ChoiceVisualizer.Models
{
    public class SemiFinalsViewModel
    {
        public List<Card<Choice>> FirstPair { get; set; }
        public List<Card<Choice>> SecondPair { get; set; }
    }
}

ChoiceVisualizer/Controllers/ChoiceController.cs
using KitProjects.ChoiceVisualizer.Models;
using KitProjects.EnterpriseLibrary.Core.Models;
using KitProjects.FileSystemChoicePreparation.PrepareFilmChoices;
using Medallion;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace KitProjects.ChoiceVisualizer.Controllers
{
    public class ChoiceController : Controller
    {
        public IActionResult Films()
        {
            ViewBag.ChoiceType = "Films";
            return PrepareCards("ChoiceVisualizer_Films");
        }

        public IActionResult Games()
        {
            ViewBag.ChoiceType = "Games";
            return PrepareCards("ChoiceVisualizer_Games");
        }

        private ViewResult PrepareCards(string directoryName)
        {
            var command = new PrepareChoicesCommand();
            var choices = command.Execute(new PrepareChoicesCommandArgs(@$"C:\Users\admin\Pictures\{directoryName}"));
            if (choices.Length >= 64)
                choices = choices.Shuffled().Take(64).ToArray();
            else if (choices.Length >= 32 && choices.Length < 64)
                choices = choices.Shuffled().Take(32).ToArray();
            else
                choices = choices.Shuffled().Take(16).ToArray();

            choices.Shuffle();
            var cards = choices.Select(choice => new Card<Choice>
            {
                Choice = choice,
                Selected = false
            });
            var firstHalf = cards.Skip(0).Take(choices.Length / 2).ToList();
            var secondHalf = cards.Skip(choices.Length / 2).Take(choices.Length / 2).ToList();
            var viewModel = new RoundViewModel
            {
                FirstHalf = firstHalf,
                SecondHalf = secondHalf
            };

            return View("Round", viewModel);
        }

        [DisableRequestSizeLimit]
        public IActionResult Round(RoundViewModel round)
        {
            if (round.FirstHalf.Count > 4)
            {
                var viewModel = new RoundViewModel
                {
                    FirstHalf = round.FirstHalf.Where(choice => choice.Selected).ToList(),
                    SecondHalf = round.SecondHalf.Where(choice => choice.Selected).ToList()
                };
                NullifySelection(viewModel.FirstHalf);
                NullifySelection(viewModel.SecondHalf);

                return View("Round", viewModel);
            }

            var semiFinalsViewModel = new SemiFinalsViewModel
            {
                FirstPair = round.FirstHalf.Where(choice => choice.Selected).ToList(),
                SecondPair = round.SecondHalf.Where(choice => choice.Selected).ToList()
            };
            NullifySelection(semiFinalsViewModel.FirstPair);
            NullifySelection(semiFinalsViewModel.SecondPair);

            return View("SemiFinals", semiFinalsViewModel);
        }

        [DisableRequestSizeLimit]
        public IActionResult SemiFinals(SemiFinalsViewModel semiFinals)
        {
            var first = semiFinals.FirstPair.First(choice => choice.Selected);
            var second = semiFinals.SecondPair.First(choice => choice.Selected);
            var thirdPlace = new List<Card<Choice>>
            {
                semiFinals.FirstPair.First(choice => choice.Selected == false),
                semiFinals.SecondPair.First(choice => choice.Selected == false)
            };
            first.Selected = false;
            second.Selected = false;
            NullifySelection(thirdPlace);

            return View("Finals", new FinalsViewModel
            {
                First = first,
                Second = second,
                ThirdPlaceContestants = thirdPlace
            });
        }

        [DisableRequestSizeLimit]
        public IActionResult Finals(FinalsViewModel finals)
        {
            var viewModel = new ResultsViewModel
            {
                ThirdPlace = finals.ThirdPlaceContestants.First(contestant => contestant.Selected)
            };
            if (finals.First.Selected)
            {
                viewModel.Winner = finals.First;
                viewModel.SecondPlace = finals.Second;
            }
            else
            {
                viewModel.Winner = finals.Second;
                viewModel.SecondPlace = finals.First;
            }
            return View("Results", viewModel);
        }

        private static void NullifySelection(IEnumerable<Card<Choice>> choices)
        {
            foreach (var choice in choices)
            {
                choice.Selected = false;
            }
        }
    }
}

ChoiceVisualizer/Controllers/HomeController.cs
using ChoiceVisualizer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ChoiceVisualizer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChoiceVisualizer/Views/Choice/Finals.cshtml
@model KitProjects.ChoiceVisualizer.Models.FinalsViewModel
<script src="~/js/fix.js">
</script>
<div id="test-carousel" class="carousel slide text-center" data-ride="false" data-interval="false" >
    <form enctype="multipart/form-data" asp-controller="Choice" asp-action="Finals" method="post" class="carousel-inner">
    <div class="carousel-item active">
        <div>
            <div style="display: flex; flex-direction:row; justify-content:space-between;">
                @{
                    string firstImage = $"data:{Model.First.Choice.Image.ContentType};base64, {Model.First.Choice.Image.Base64}";
                    string secondImage = $"data:{Model.Second.Choice.Image.ContentType};base64, {Model.Second.Choice.Image.Base64}";
                    string firstImageId = Model.First.Choice.Title;
                    string secondImageId = Model.Second.Choice.Title;
                }
                <figure>
                    <label class="form-check-label" for="@firstImageId">
                        <img class="choice-image" src="@firstImage" alt="Картинка" />
                    </label>
                    <figcaption>
                        <input id="@firstImageId" class="form-check-input" name="First.Selected" type="checkbox" value="true" />
                        @Model.First.Choice.Title <br />
                    </figcaption>
                </figure>
                <figure>
                    <label class="form-check-label" for="@secondImageId">
                        <img class="choice-image" src="@secondImage" alt="Картинка" />
                    </label>
                    <figcaption>
                        <input id="@secondImageId" class="form-check-input" name="Second.Selected" type="checkbox" value="true" />
                        @Model.Second.Choice.Title
                    </figcaption>
                </figure>
            </div>
        </div>
        <input type="hidden" name="First.Choice.Title" value="@Model.First.Choice.Title" />
        <input type="hidden" name="First.Choice.Image.Base64" value="@Model.First.Choice.Image.Base64" />
        <input type="hidden" name="First.Choice.Image.ContentType" value="@Model.First.Choice.Image.ContentType" />
        <input type="hidden" name="First.Choice.Image.Link" value="@Model.First.Choice.Image.Link" />
        <input type="hidden" name="Second.Choice.Title" value="@Model.Second.Choice.Title" />
        <input type="hidden" name="Second.Choice.Image.Base64" value="@Model.Second.Choice.Image.Base64" />
        <input type="hidden" name="Second.Choice.Image.ContentType" value="@Model.Second.Choice.Image.ContentType" />
        <input type="hidden" name="Second.Choice.Image.Link" value="@Model.Second.Choice.Image.Link" />
    </div>
        @{
            ViewBag.ChoicesArrayName = nameof(Model.ThirdPlaceContestants);
            await Html.RenderPartialAsync("_Half", Model.ThirdPlaceContestants);
        }
    <input id="submit-test" type="submit" style="display: none;" />
        <a class="carousel-control-prev" href="#test-carousel" role="button" data-slide="prev">
            <span class="btn btn-info">Назад</span>
        </a>
        <a class="carousel-control-next" href="#test-carousel" role="button" data-slide="next">
            <span class="btn btn-info">Дальше</span>
        </a>
</form>
</div>
<button class="submit-test-button btn btn-success" onclick="document.getElementById('submit-test').click()">Готово!</button>
<script>
    fixCarouselItems();
</script>

ChoiceVisualizer/Views/Choice/Results.cshtml
@model KitProjects.ChoiceVisualizer.Models.ResultsViewModel
<ol class="results">
    <li class="result">
        <img src="@($"data:{Model.Winner.Choice.Image.ContentType};base64, {Model.Winner.Choice.Image.Base64}")" />
        <p>
            @Model.Winner.Choice.Title
        </p>
    </li>
    <li class="result">
        <img src="@($"data:{Model.SecondPlace.Choice.Image.ContentType};base64, {Model.SecondPlace.Choice.Image.Base64}")" />
        <p>
            @Model.SecondPlace.Choice.Title
        </p>
    </li>
    <li class="result">
        <img src="@($"data:{Model.ThirdPlace.Choice.Image.ContentType};base64, {Model.ThirdPlace.Choice.Image.Base64}")" />
        <p>
            @Model.ThirdPlace.Choice.Title
        </p>
    </li>
</ol>

ChoiceVisualizer/Views/Choice/Round.cshtml
@model KitProjects.ChoiceVisualizer.Models.RoundViewModel
<script src="~/js/fix.js"></script>

<div id="test-carousel" class="carousel slide text-center" data-ride="false" data-interval="false" >
    <form enctype="multipart/form-data" asp-controller="Choice" asp-action="Round" method="post" class="carousel-inner">
        @{
            ViewBag.ChoicesArrayName = nameof(Model.FirstHalf);
            await Html.RenderPartialAsync("_Half", Model.FirstHalf);
        }

        @{
            ViewBag.ChoicesArrayName = nameof(Model.SecondHalf);
            await Html.RenderPartialAsync("_Half", Model.SecondHalf);
        }

        <input id="submit-test" type="submit" style="display: none;" />
        <a class="carousel-control-prev" href="#test-carousel" role="button" data-slide="prev">
            <span class="btn btn-info">Назад</span>
        </a>
        <a class="carousel-control-next" href="#test-carousel" role="button" data-slide="next">
            <span class="btn btn-info">Дальше</span>
        </a>
    </form>
</div>
<button class="submit-test-button btn btn-success" onclick="document.getElementById('submit-test').click()">Готово!</button>
<script>
    fixCarouselItems();
</script>

<!--
    Сделать управление стрелками без
-->

ChoiceVisualizer/Views/Choice/SemiFinals.cshtml
@model KitProjects.ChoiceVisualizer.Models.SemiFinalsViewModel
<script src="~/js/fix.js"></script>

<div id="test-carousel" class="carousel slide text-center" data-ride="false" data-interval="false" >
    <form enctype="multipart/form-data" asp-controller="Choice" asp-action="SemiFinals" method="post" class="carousel-inner">
        @{
            ViewBag.ChoicesArrayName = nameof(Model.FirstPair);
            await Html.RenderPartialAsync("_Half", Model.FirstPair);
        }
        @{
            ViewBag.ChoicesArrayName = nameof(Model.SecondPair);
            await Html.RenderPartialAsync("_Half", Model.SecondPair);
        }

        <input id="submit-test" type="submit" style="display: none;" />
        <a class="carousel-control-prev" href="#test-carousel" role="button" data-slide="prev">
            <span class="btn btn-info">Назад</span>
        </a>
        <a class="carousel-control-next" href="#test-carousel" role="button" data-slide="next">
            <span class="btn btn-info">Дальше</span>
        </a>
    </form>
</div>
<button class="submit-test-button btn btn-success" onclick="document.getElementById('submit-test').click()">Готово!</button>
<script>fixCarouselItems();</script>

ChoiceVisualizer/Views/Choice/_Half.cshtml
@using KitProjects.ChoiceVisualizer.Models
@using KitProjects.EnterpriseLibrary.Core.Models

@model List<Card<Choice>>

@{
    string choicesArrayName = ViewBag.ChoicesArrayName;
}

@for (int i = 0; i < Model.Count; i += 2)
{
    string carousel_item_class = i == 0 ? "carousel-item active" : "carousel-item";
    string firstImageId = Model[i].Choice.Title;
    string secondImageId = Model[i + 1].Choice.Title;
    <div class="@carousel_item_class">
        <div>
            <div style="display: flex; flex-direction:row; justify-content:space-between;">
                @{
                    string firstImage = $"data:{Model[i].Choice.Image.ContentType};base64, {Model[i].Choice.Image.Base64}";
                    string secondImage = $"data:{Model[i + 1].Choice.Image.ContentType};base64, {Model[i + 1].Choice.Image.Base64}";
                }
                <figure>
                    <label class="form-check-label" for="@firstImageId">
                        <img class="choice-image" src="@firstImage" alt="Картинка" />
                    </label>
                    <figcaption>
                        <input id="@firstImageId" class="form-check-input" name="@(choicesArrayName)[@i].Selected" type="checkbox" value="true"/>
                        @Model[i].Choice.Title <br />
                    </figcaption>
                </figure>
                <figure>
                    <label class="form-check-label" for="@secondImageId">
                        <img class="choice-image" src="@secondImage" alt="Картинка" />
                    </label>
                    <figcaption>
                        <input id="@secondImageId" class="form-check-input" name="@(choicesArrayName)[@(i + 1)].Selected" type="checkbox" value="true"/>
                        @Model[i + 1].Choice.Title
                    </figcaption>
                </figure>
            </div>
        </div>
        <input type="hidden" name="@(choicesArrayName)[@i].Choice.Title" value="@Model[i].Choice.Title" />
        <input type="hidden" name="@(choicesArrayName)[@i].Choice.Image.Base64" value="@Model[i].Choice.Image.Base64" />
        <input type="hidden" name="@(choicesArrayName)[@i].Choice.Image.ContentType" value="@Model[i].Choice.Image.ContentType" />
        <input type="hidden" name="@(choicesArrayName)[@i].Choice.Image.Link" value="@Model[i].Choice.Image.Link" />
        <input type="hidden" name="@(choicesArrayName)[@(i + 1)].Choice.Title" value="@Model[i + 1].Choice.Title" />
        <input type="hidden" name="@(choicesArrayName)[@(i + 1)].Choice.Image.Base64" value="@Model[i + 1].Choice.Image.Base64" />
        <input type="hidden" name="@(choicesArrayName)[@(i + 1)].Choice.Image.ContentType" value="@Model[i + 1].Choice.Image.ContentType" />
        <input type="hidden" name="@(choicesArrayName)[@(i + 1)].Choice.Image.Link" value="@Model[i + 1].Choice.Image.Link" />
    </div>
}

ChoiceVisualizer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ChoiceVisualizer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChoiceVisualizer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChoiceVisualizer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Choice" asp-action="Films">Фильмы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Choice" asp-action="Games">Игры</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-muted" asp-area="" asp-controller="Choice" asp-action="Music">Музыка</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ChoiceVisualizer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>